// Generated by gencpp from file ros_threads/GiveTimeResponse.msg
// DO NOT EDIT!


#ifndef ROS_THREADS_MESSAGE_GIVETIMERESPONSE_H
#define ROS_THREADS_MESSAGE_GIVETIMERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_threads
{
template <class ContainerAllocator>
struct GiveTimeResponse_
{
  typedef GiveTimeResponse_<ContainerAllocator> Type;

  GiveTimeResponse_()
    : Time_str()  {
    }
  GiveTimeResponse_(const ContainerAllocator& _alloc)
    : Time_str(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Time_str_type;
  _Time_str_type Time_str;





  typedef boost::shared_ptr< ::ros_threads::GiveTimeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_threads::GiveTimeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GiveTimeResponse_

typedef ::ros_threads::GiveTimeResponse_<std::allocator<void> > GiveTimeResponse;

typedef boost::shared_ptr< ::ros_threads::GiveTimeResponse > GiveTimeResponsePtr;
typedef boost::shared_ptr< ::ros_threads::GiveTimeResponse const> GiveTimeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_threads::GiveTimeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_threads::GiveTimeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_threads

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_threads::GiveTimeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_threads::GiveTimeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_threads::GiveTimeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_threads::GiveTimeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_threads::GiveTimeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_threads::GiveTimeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_threads::GiveTimeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d739f867d84b6419fed8a84a9f73e83";
  }

  static const char* value(const ::ros_threads::GiveTimeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d739f867d84b641ULL;
  static const uint64_t static_value2 = 0x9fed8a84a9f73e83ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_threads::GiveTimeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_threads/GiveTimeResponse";
  }

  static const char* value(const ::ros_threads::GiveTimeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_threads::GiveTimeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Time_str\n\
\n\
";
  }

  static const char* value(const ::ros_threads::GiveTimeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_threads::GiveTimeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Time_str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GiveTimeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_threads::GiveTimeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_threads::GiveTimeResponse_<ContainerAllocator>& v)
  {
    s << indent << "Time_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Time_str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_THREADS_MESSAGE_GIVETIMERESPONSE_H
