// Generated by gencpp from file ros_threads/GiveTimeRequest.msg
// DO NOT EDIT!


#ifndef ROS_THREADS_MESSAGE_GIVETIMEREQUEST_H
#define ROS_THREADS_MESSAGE_GIVETIMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_threads
{
template <class ContainerAllocator>
struct GiveTimeRequest_
{
  typedef GiveTimeRequest_<ContainerAllocator> Type;

  GiveTimeRequest_()
    : Delay_s(0)  {
    }
  GiveTimeRequest_(const ContainerAllocator& _alloc)
    : Delay_s(0)  {
  (void)_alloc;
    }



   typedef int64_t _Delay_s_type;
  _Delay_s_type Delay_s;





  typedef boost::shared_ptr< ::ros_threads::GiveTimeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_threads::GiveTimeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GiveTimeRequest_

typedef ::ros_threads::GiveTimeRequest_<std::allocator<void> > GiveTimeRequest;

typedef boost::shared_ptr< ::ros_threads::GiveTimeRequest > GiveTimeRequestPtr;
typedef boost::shared_ptr< ::ros_threads::GiveTimeRequest const> GiveTimeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_threads::GiveTimeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_threads::GiveTimeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_threads

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_threads::GiveTimeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_threads::GiveTimeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_threads::GiveTimeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_threads::GiveTimeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_threads::GiveTimeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_threads::GiveTimeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_threads::GiveTimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a1ca202dab30bdc43d00f5365748e22";
  }

  static const char* value(const ::ros_threads::GiveTimeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a1ca202dab30bdcULL;
  static const uint64_t static_value2 = 0x43d00f5365748e22ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_threads::GiveTimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_threads/GiveTimeRequest";
  }

  static const char* value(const ::ros_threads::GiveTimeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_threads::GiveTimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 Delay_s\n\
";
  }

  static const char* value(const ::ros_threads::GiveTimeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_threads::GiveTimeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Delay_s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GiveTimeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_threads::GiveTimeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_threads::GiveTimeRequest_<ContainerAllocator>& v)
  {
    s << indent << "Delay_s: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Delay_s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_THREADS_MESSAGE_GIVETIMEREQUEST_H
